version: "3.9"
services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=mycashdb
  service:
    container_name: server
    build:
      context: .
    expose:
      - 8080
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mycashdb
      - DB_USER=postgres
      - DB_PASS=postgrespw
      - SERVER_PORT=8080

  nginx:
    build: ./nginx
    ports:
      - "4080:80"
    depends_on:
      - service